name = "shop-and-son-now-playing"
main = "src/index.js"
compatibility_date = "2026-07-07"
workers_dev = true

[vars]
SPOTIFY_CLIENT_ID = "8890a3933d484ade825a44278a8f5792"
ALLOWED_DEVICES = "Benjamin's iPad"

[[kv_namespaces]]
binding = "NOW_PLAYING_KV"
id = "00000000000000000000000000000000"
